FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

RUN apt-get update && apt-get install -y \
    git \
    python3.10 \
    python3.10-venv \
    python3-pip \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements*.txt .

RUN pip install -r requirements.txt && \
    pip install --no-build-isolation -r requirements_flash_attn.txt

CMD ["jupyter-lab", "--allow-root", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--NotebookApp.token=''"]
